In [2]:
#Loader
import pandas as pd
import matplotlib.pyplot as plt
from kloppy import pff

# paths to data files
roster_path = "/home/student/Documents/AIMS/Intership/pysport/pysport-aims/first_week/data/3812/3812_roster.json"
metadata_path = "/home/student/Documents/AIMS/Intership/pysport/pysport-aims/first_week/data/3812/3812_metadata.json"
raw_data_path = "/home/student/Documents/AIMS/Intership/pysport/pysport-aims/first_week/data/3812/3812.jsonl.bz2"

In [3]:
# Load the dataset for match ID 3812.
dataset = pff.load_tracking(
    raw_data = raw_data_path,
    meta_data = metadata_path,
    roster_meta_data = roster_path,
    coordinates= "pff",
    limit= None,
    sample_rate= None
)

dataset.to_df().head(5)

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,13228_x,...,8033_d,8033_s,8326_x,8326_y,8326_d,8326_s,8327_x,8327_y,8327_d,8327_s
0,1,0 days 00:00:00,4226,alive,366,2.46,1.58,0.0,None,14.357,...,None,None,NaN,NaN,None,None,NaN,NaN,None,None
1,1,0 days 00:00:00.033041,4227,alive,366,2.04,1.62,0.0,None,14.335,...,None,None,NaN,NaN,None,None,NaN,NaN,None,None
2,1,0 days 00:00:00.066408,4228,alive,366,1.62,1.67,0.0,None,14.313,...,None,None,NaN,NaN,None,None,NaN,NaN,None,None
3,1,0 days 00:00:00.099774,4229,alive,366,1.20,1.71,0.0,None,14.291,...,None,None,NaN,NaN,None,None,NaN,NaN,None,None
4,1,0 days 00:00:00.133141,4230,alive,366,0.78,1.76,0.0,None,14.270,...,None,None,NaN,NaN,None,None,NaN,NaN,None,None

In [7]:
# try the example in the documentation to get frames where the ball is in the tirth part of the fiels
pitch_lenght = dataset.metadata.pitch_dimensions.pitch_length
sub_dataset  = dataset.filter(
    lambda frame: frame.ball_coordinates.x > 2/3*pitch_lenght
)

AttributeError: 'NoneType' object has no attribute 'x'

In [16]:
# check if we get well the ball_coordinate
frame0 = 0
for frame in dataset.frames:
    frame0 = frame.ball_coordinates
    print(type(frame.ball_coordinates))
    break

<class 'kloppy.domain.models.pitch.Point3D'>

In [18]:
# now why can't we not access to the x attribute ?
frame0.x

2.46